# Generated by Django 4.0 on 2021-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccounts',
            new_name='Accounts',
        ),
    ]
