# Generated by Django 4.0 on 2021-12-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_useraccounts_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
